/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TargetActionTypesRouteImport } from './routes/target-action-types'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignalTypesRouteImport } from './routes/signal-types'
import { Route as SalesPlansRouteImport } from './routes/sales-plans'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RefusalReasonsRouteImport } from './routes/refusal-reasons'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as MyCompanyRouteImport } from './routes/my-company'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MeetingRoomsRouteImport } from './routes/meeting-rooms'
import { Route as MailingListsRouteImport } from './routes/mailing-lists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadSourcesRouteImport } from './routes/lead-sources'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRolesRouteImport } from './routes/contact-roles'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WishlistNewRouteImport } from './routes/wishlist.new'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as TodosNewRouteImport } from './routes/todos.new'
import { Route as TendersNewRouteImport } from './routes/tenders.new'
import { Route as TargetActionTypesNewRouteImport } from './routes/target-action-types.new'
import { Route as TagsNewRouteImport } from './routes/tags.new'
import { Route as SignalsNewRouteImport } from './routes/signals.new'
import { Route as SignalTypesNewRouteImport } from './routes/signal-types.new'
import { Route as SalesPlansNewRouteImport } from './routes/sales-plans.new'
import { Route as ReportsTargetActionsRouteImport } from './routes/reports_.target-actions'
import { Route as ReportsPlanFactRouteImport } from './routes/reports_.plan-fact'
import { Route as RefusalReasonsNewRouteImport } from './routes/refusal-reasons.new'
import { Route as MyCompanyNewRouteImport } from './routes/my-company.new'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'
import { Route as MeetingRoomsNewRouteImport } from './routes/meeting-rooms.new'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadSourcesNewRouteImport } from './routes/lead-sources.new'
import { Route as InitiativesNewRouteImport } from './routes/initiatives.new'
import { Route as IndustriesNewRouteImport } from './routes/industries.new'
import { Route as ContactRolesNewRouteImport } from './routes/contact-roles.new'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ChangelogNewRouteImport } from './routes/changelog.new'
import { Route as WishlistIdViewRouteImport } from './routes/wishlist_.$id.view'
import { Route as WishlistIdUpdateRouteImport } from './routes/wishlist.$id.update'
import { Route as WishlistIdDeleteRouteImport } from './routes/wishlist.$id.delete'
import { Route as UsersIdUpdateRouteImport } from './routes/users.$id.update'
import { Route as UsersIdUnbanRouteImport } from './routes/users.$id.unban'
import { Route as UsersIdResetPasswordRouteImport } from './routes/users.$id.reset-password'
import { Route as UsersIdDeleteRouteImport } from './routes/users.$id.delete'
import { Route as UsersIdBanRouteImport } from './routes/users.$id.ban'
import { Route as TodosIdViewRouteImport } from './routes/todos_.$id.view'
import { Route as TodosIdUpdateRouteImport } from './routes/todos.$id.update'
import { Route as TodosIdDeleteRouteImport } from './routes/todos.$id.delete'
import { Route as TendersIdViewRouteImport } from './routes/tenders_.$id.view'
import { Route as TendersIdUpdateRouteImport } from './routes/tenders.$id.update'
import { Route as TendersIdDeleteRouteImport } from './routes/tenders.$id.delete'
import { Route as TargetActionTypesIdUpdateRouteImport } from './routes/target-action-types.$id.update'
import { Route as TargetActionTypesIdDeleteRouteImport } from './routes/target-action-types.$id.delete'
import { Route as TagsIdUpdateRouteImport } from './routes/tags.$id.update'
import { Route as TagsIdDeleteRouteImport } from './routes/tags.$id.delete'
import { Route as SignalsIdViewRouteImport } from './routes/signals_.$id.view'
import { Route as SignalsIdUpdateRouteImport } from './routes/signals.$id.update'
import { Route as SignalsIdDeleteRouteImport } from './routes/signals.$id.delete'
import { Route as SignalTypesIdUpdateRouteImport } from './routes/signal-types.$id.update'
import { Route as SignalTypesIdDeleteRouteImport } from './routes/signal-types.$id.delete'
import { Route as SalesPlansIdUpdateRouteImport } from './routes/sales-plans.$id.update'
import { Route as SalesPlansIdDeleteRouteImport } from './routes/sales-plans.$id.delete'
import { Route as RefusalReasonsIdUpdateRouteImport } from './routes/refusal-reasons.$id.update'
import { Route as RefusalReasonsIdDeleteRouteImport } from './routes/refusal-reasons.$id.delete'
import { Route as MyCompanyIdViewRouteImport } from './routes/my-company_.$id.view'
import { Route as MyCompanyIdUpdateRouteImport } from './routes/my-company.$id.update'
import { Route as MyCompanyIdDeleteRouteImport } from './routes/my-company.$id.delete'
import { Route as MeetingsIdViewRouteImport } from './routes/meetings.$id.view'
import { Route as MeetingsIdUpdateRouteImport } from './routes/meetings.$id.update'
import { Route as MeetingsIdDeleteRouteImport } from './routes/meetings.$id.delete'
import { Route as MeetingsIdCopyRouteImport } from './routes/meetings.$id.copy'
import { Route as MeetingRoomsIdUpdateRouteImport } from './routes/meeting-rooms.$id.update'
import { Route as MeetingRoomsIdDeleteRouteImport } from './routes/meeting-rooms.$id.delete'
import { Route as LeadsIdViewRouteImport } from './routes/leads_.$id.view'
import { Route as LeadsIdUpdateRouteImport } from './routes/leads.$id.update'
import { Route as LeadsIdDeleteRouteImport } from './routes/leads.$id.delete'
import { Route as LeadSourcesIdUpdateRouteImport } from './routes/lead-sources.$id.update'
import { Route as LeadSourcesIdDeleteRouteImport } from './routes/lead-sources.$id.delete'
import { Route as InitiativesIdViewRouteImport } from './routes/initiatives.$id.view'
import { Route as InitiativesIdUpdateRouteImport } from './routes/initiatives.$id.update'
import { Route as InitiativesIdDeleteRouteImport } from './routes/initiatives.$id.delete'
import { Route as IndustriesIdUpdateRouteImport } from './routes/industries.$id.update'
import { Route as IndustriesIdDeleteRouteImport } from './routes/industries.$id.delete'
import { Route as ContactRolesIdUpdateRouteImport } from './routes/contact-roles.$id.update'
import { Route as ContactRolesIdDeleteRouteImport } from './routes/contact-roles.$id.delete'
import { Route as CompaniesIdViewRouteImport } from './routes/companies_.$id.view'
import { Route as CompaniesIdUpdateRouteImport } from './routes/companies.$id.update'
import { Route as CompaniesIdDeleteRouteImport } from './routes/companies.$id.delete'
import { Route as ClientsIdViewRouteImport } from './routes/clients_.$id.view'
import { Route as ClientsIdUpdateRouteImport } from './routes/clients.$id.update'
import { Route as ClientsIdDeleteRouteImport } from './routes/clients.$id.delete'
import { Route as ChangelogIdUpdateRouteImport } from './routes/changelog.$id.update'
import { Route as ChangelogIdDeleteRouteImport } from './routes/changelog.$id.delete'
import { Route as ApiPingSplatRouteImport } from './routes/api/ping/$'
import { Route as ApiMeetingsSplatRouteImport } from './routes/api/meetings/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetActionTypesRoute = TargetActionTypesRouteImport.update({
  id: '/target-action-types',
  path: '/target-action-types',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalTypesRoute = SignalTypesRouteImport.update({
  id: '/signal-types',
  path: '/signal-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPlansRoute = SalesPlansRouteImport.update({
  id: '/sales-plans',
  path: '/sales-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusalReasonsRoute = RefusalReasonsRouteImport.update({
  id: '/refusal-reasons',
  path: '/refusal-reasons',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompanyRoute = MyCompanyRouteImport.update({
  id: '/my-company',
  path: '/my-company',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoomsRoute = MeetingRoomsRouteImport.update({
  id: '/meeting-rooms',
  path: '/meeting-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const MailingListsRoute = MailingListsRouteImport.update({
  id: '/mailing-lists',
  path: '/mailing-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSourcesRoute = LeadSourcesRouteImport.update({
  id: '/lead-sources',
  path: '/lead-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRolesRoute = ContactRolesRouteImport.update({
  id: '/contact-roles',
  path: '/contact-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistNewRoute = WishlistNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WishlistRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TodosRoute,
} as any)
const TendersNewRoute = TendersNewRouteImport.update({
  id: '/tenders/new',
  path: '/tenders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetActionTypesNewRoute = TargetActionTypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TargetActionTypesRoute,
} as any)
const TagsNewRoute = TagsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TagsRoute,
} as any)
const SignalsNewRoute = SignalsNewRouteImport.update({
  id: '/signals/new',
  path: '/signals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalTypesNewRoute = SignalTypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SignalTypesRoute,
} as any)
const SalesPlansNewRoute = SalesPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesPlansRoute,
} as any)
const ReportsTargetActionsRoute = ReportsTargetActionsRouteImport.update({
  id: '/reports_/target-actions',
  path: '/reports/target-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPlanFactRoute = ReportsPlanFactRouteImport.update({
  id: '/reports_/plan-fact',
  path: '/reports/plan-fact',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusalReasonsNewRoute = RefusalReasonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RefusalReasonsRoute,
} as any)
const MyCompanyNewRoute = MyCompanyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MyCompanyRoute,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingRoomsNewRoute = MeetingRoomsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MeetingRoomsRoute,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSourcesNewRoute = LeadSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LeadSourcesRoute,
} as any)
const InitiativesNewRoute = InitiativesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InitiativesRoute,
} as any)
const IndustriesNewRoute = IndustriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IndustriesRoute,
} as any)
const ContactRolesNewRoute = ContactRolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContactRolesRoute,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ChangelogNewRoute = ChangelogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChangelogRoute,
} as any)
const WishlistIdViewRoute = WishlistIdViewRouteImport.update({
  id: '/wishlist_/$id/view',
  path: '/wishlist/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistIdUpdateRoute = WishlistIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => WishlistRoute,
} as any)
const WishlistIdDeleteRoute = WishlistIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => WishlistRoute,
} as any)
const UsersIdUpdateRoute = UsersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdUnbanRoute = UsersIdUnbanRouteImport.update({
  id: '/$id/unban',
  path: '/$id/unban',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdResetPasswordRoute = UsersIdResetPasswordRouteImport.update({
  id: '/$id/reset-password',
  path: '/$id/reset-password',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdDeleteRoute = UsersIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdBanRoute = UsersIdBanRouteImport.update({
  id: '/$id/ban',
  path: '/$id/ban',
  getParentRoute: () => UsersRoute,
} as any)
const TodosIdViewRoute = TodosIdViewRouteImport.update({
  id: '/todos_/$id/view',
  path: '/todos/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdUpdateRoute = TodosIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => TodosRoute,
} as any)
const TodosIdDeleteRoute = TodosIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => TodosRoute,
} as any)
const TendersIdViewRoute = TendersIdViewRouteImport.update({
  id: '/tenders_/$id/view',
  path: '/tenders/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIdUpdateRoute = TendersIdUpdateRouteImport.update({
  id: '/tenders/$id/update',
  path: '/tenders/$id/update',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIdDeleteRoute = TendersIdDeleteRouteImport.update({
  id: '/tenders/$id/delete',
  path: '/tenders/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetActionTypesIdUpdateRoute =
  TargetActionTypesIdUpdateRouteImport.update({
    id: '/$id/update',
    path: '/$id/update',
    getParentRoute: () => TargetActionTypesRoute,
  } as any)
const TargetActionTypesIdDeleteRoute =
  TargetActionTypesIdDeleteRouteImport.update({
    id: '/$id/delete',
    path: '/$id/delete',
    getParentRoute: () => TargetActionTypesRoute,
  } as any)
const TagsIdUpdateRoute = TagsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => TagsRoute,
} as any)
const TagsIdDeleteRoute = TagsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => TagsRoute,
} as any)
const SignalsIdViewRoute = SignalsIdViewRouteImport.update({
  id: '/signals_/$id/view',
  path: '/signals/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIdUpdateRoute = SignalsIdUpdateRouteImport.update({
  id: '/signals/$id/update',
  path: '/signals/$id/update',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIdDeleteRoute = SignalsIdDeleteRouteImport.update({
  id: '/signals/$id/delete',
  path: '/signals/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalTypesIdUpdateRoute = SignalTypesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => SignalTypesRoute,
} as any)
const SignalTypesIdDeleteRoute = SignalTypesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => SignalTypesRoute,
} as any)
const SalesPlansIdUpdateRoute = SalesPlansIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => SalesPlansRoute,
} as any)
const SalesPlansIdDeleteRoute = SalesPlansIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => SalesPlansRoute,
} as any)
const RefusalReasonsIdUpdateRoute = RefusalReasonsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => RefusalReasonsRoute,
} as any)
const RefusalReasonsIdDeleteRoute = RefusalReasonsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => RefusalReasonsRoute,
} as any)
const MyCompanyIdViewRoute = MyCompanyIdViewRouteImport.update({
  id: '/my-company_/$id/view',
  path: '/my-company/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompanyIdUpdateRoute = MyCompanyIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => MyCompanyRoute,
} as any)
const MyCompanyIdDeleteRoute = MyCompanyIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => MyCompanyRoute,
} as any)
const MeetingsIdViewRoute = MeetingsIdViewRouteImport.update({
  id: '/$id/view',
  path: '/$id/view',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsIdUpdateRoute = MeetingsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsIdDeleteRoute = MeetingsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsIdCopyRoute = MeetingsIdCopyRouteImport.update({
  id: '/$id/copy',
  path: '/$id/copy',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingRoomsIdUpdateRoute = MeetingRoomsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => MeetingRoomsRoute,
} as any)
const MeetingRoomsIdDeleteRoute = MeetingRoomsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => MeetingRoomsRoute,
} as any)
const LeadsIdViewRoute = LeadsIdViewRouteImport.update({
  id: '/leads_/$id/view',
  path: '/leads/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdUpdateRoute = LeadsIdUpdateRouteImport.update({
  id: '/leads/$id/update',
  path: '/leads/$id/update',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdDeleteRoute = LeadsIdDeleteRouteImport.update({
  id: '/leads/$id/delete',
  path: '/leads/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSourcesIdUpdateRoute = LeadSourcesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => LeadSourcesRoute,
} as any)
const LeadSourcesIdDeleteRoute = LeadSourcesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => LeadSourcesRoute,
} as any)
const InitiativesIdViewRoute = InitiativesIdViewRouteImport.update({
  id: '/$id/view',
  path: '/$id/view',
  getParentRoute: () => InitiativesRoute,
} as any)
const InitiativesIdUpdateRoute = InitiativesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => InitiativesRoute,
} as any)
const InitiativesIdDeleteRoute = InitiativesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => InitiativesRoute,
} as any)
const IndustriesIdUpdateRoute = IndustriesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesIdDeleteRoute = IndustriesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => IndustriesRoute,
} as any)
const ContactRolesIdUpdateRoute = ContactRolesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => ContactRolesRoute,
} as any)
const ContactRolesIdDeleteRoute = ContactRolesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ContactRolesRoute,
} as any)
const CompaniesIdViewRoute = CompaniesIdViewRouteImport.update({
  id: '/companies_/$id/view',
  path: '/companies/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdUpdateRoute = CompaniesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesIdDeleteRoute = CompaniesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => CompaniesRoute,
} as any)
const ClientsIdViewRoute = ClientsIdViewRouteImport.update({
  id: '/clients_/$id/view',
  path: '/clients/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdUpdateRoute = ClientsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIdDeleteRoute = ClientsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ClientsRoute,
} as any)
const ChangelogIdUpdateRoute = ChangelogIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => ChangelogRoute,
} as any)
const ChangelogIdDeleteRoute = ChangelogIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ChangelogRoute,
} as any)
const ApiPingSplatRoute = ApiPingSplatRouteImport.update({
  id: '/api/ping/$',
  path: '/api/ping/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsSplatRoute = ApiMeetingsSplatRouteImport.update({
  id: '/api/meetings/$',
  path: '/api/meetings/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contact-roles': typeof ContactRolesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/initiatives': typeof InitiativesRouteWithChildren
  '/lead-sources': typeof LeadSourcesRouteWithChildren
  '/login': typeof LoginRoute
  '/mailing-lists': typeof MailingListsRoute
  '/meeting-rooms': typeof MeetingRoomsRouteWithChildren
  '/meetings': typeof MeetingsRouteWithChildren
  '/my-company': typeof MyCompanyRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/refusal-reasons': typeof RefusalReasonsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales-plans': typeof SalesPlansRouteWithChildren
  '/signal-types': typeof SignalTypesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRoute
  '/tags': typeof TagsRouteWithChildren
  '/target-action-types': typeof TargetActionTypesRouteWithChildren
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRouteWithChildren
  '/changelog/new': typeof ChangelogNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contact-roles/new': typeof ContactRolesNewRoute
  '/industries/new': typeof IndustriesNewRoute
  '/initiatives/new': typeof InitiativesNewRoute
  '/lead-sources/new': typeof LeadSourcesNewRoute
  '/leads/new': typeof LeadsNewRoute
  '/meeting-rooms/new': typeof MeetingRoomsNewRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/my-company/new': typeof MyCompanyNewRoute
  '/refusal-reasons/new': typeof RefusalReasonsNewRoute
  '/reports/plan-fact': typeof ReportsPlanFactRoute
  '/reports/target-actions': typeof ReportsTargetActionsRoute
  '/sales-plans/new': typeof SalesPlansNewRoute
  '/signal-types/new': typeof SignalTypesNewRoute
  '/signals/new': typeof SignalsNewRoute
  '/tags/new': typeof TagsNewRoute
  '/target-action-types/new': typeof TargetActionTypesNewRoute
  '/tenders/new': typeof TendersNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/wishlist/new': typeof WishlistNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meetings/$': typeof ApiMeetingsSplatRoute
  '/api/ping/$': typeof ApiPingSplatRoute
  '/changelog/$id/delete': typeof ChangelogIdDeleteRoute
  '/changelog/$id/update': typeof ChangelogIdUpdateRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies/$id/view': typeof CompaniesIdViewRoute
  '/contact-roles/$id/delete': typeof ContactRolesIdDeleteRoute
  '/contact-roles/$id/update': typeof ContactRolesIdUpdateRoute
  '/industries/$id/delete': typeof IndustriesIdDeleteRoute
  '/industries/$id/update': typeof IndustriesIdUpdateRoute
  '/initiatives/$id/delete': typeof InitiativesIdDeleteRoute
  '/initiatives/$id/update': typeof InitiativesIdUpdateRoute
  '/initiatives/$id/view': typeof InitiativesIdViewRoute
  '/lead-sources/$id/delete': typeof LeadSourcesIdDeleteRoute
  '/lead-sources/$id/update': typeof LeadSourcesIdUpdateRoute
  '/leads/$id/delete': typeof LeadsIdDeleteRoute
  '/leads/$id/update': typeof LeadsIdUpdateRoute
  '/leads/$id/view': typeof LeadsIdViewRoute
  '/meeting-rooms/$id/delete': typeof MeetingRoomsIdDeleteRoute
  '/meeting-rooms/$id/update': typeof MeetingRoomsIdUpdateRoute
  '/meetings/$id/copy': typeof MeetingsIdCopyRoute
  '/meetings/$id/delete': typeof MeetingsIdDeleteRoute
  '/meetings/$id/update': typeof MeetingsIdUpdateRoute
  '/meetings/$id/view': typeof MeetingsIdViewRoute
  '/my-company/$id/delete': typeof MyCompanyIdDeleteRoute
  '/my-company/$id/update': typeof MyCompanyIdUpdateRoute
  '/my-company/$id/view': typeof MyCompanyIdViewRoute
  '/refusal-reasons/$id/delete': typeof RefusalReasonsIdDeleteRoute
  '/refusal-reasons/$id/update': typeof RefusalReasonsIdUpdateRoute
  '/sales-plans/$id/delete': typeof SalesPlansIdDeleteRoute
  '/sales-plans/$id/update': typeof SalesPlansIdUpdateRoute
  '/signal-types/$id/delete': typeof SignalTypesIdDeleteRoute
  '/signal-types/$id/update': typeof SignalTypesIdUpdateRoute
  '/signals/$id/delete': typeof SignalsIdDeleteRoute
  '/signals/$id/update': typeof SignalsIdUpdateRoute
  '/signals/$id/view': typeof SignalsIdViewRoute
  '/tags/$id/delete': typeof TagsIdDeleteRoute
  '/tags/$id/update': typeof TagsIdUpdateRoute
  '/target-action-types/$id/delete': typeof TargetActionTypesIdDeleteRoute
  '/target-action-types/$id/update': typeof TargetActionTypesIdUpdateRoute
  '/tenders/$id/delete': typeof TendersIdDeleteRoute
  '/tenders/$id/update': typeof TendersIdUpdateRoute
  '/tenders/$id/view': typeof TendersIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/reset-password': typeof UsersIdResetPasswordRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
  '/wishlist/$id/delete': typeof WishlistIdDeleteRoute
  '/wishlist/$id/update': typeof WishlistIdUpdateRoute
  '/wishlist/$id/view': typeof WishlistIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contact-roles': typeof ContactRolesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/initiatives': typeof InitiativesRouteWithChildren
  '/lead-sources': typeof LeadSourcesRouteWithChildren
  '/login': typeof LoginRoute
  '/mailing-lists': typeof MailingListsRoute
  '/meeting-rooms': typeof MeetingRoomsRouteWithChildren
  '/meetings': typeof MeetingsRouteWithChildren
  '/my-company': typeof MyCompanyRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/refusal-reasons': typeof RefusalReasonsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales-plans': typeof SalesPlansRouteWithChildren
  '/signal-types': typeof SignalTypesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRoute
  '/tags': typeof TagsRouteWithChildren
  '/target-action-types': typeof TargetActionTypesRouteWithChildren
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRouteWithChildren
  '/changelog/new': typeof ChangelogNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contact-roles/new': typeof ContactRolesNewRoute
  '/industries/new': typeof IndustriesNewRoute
  '/initiatives/new': typeof InitiativesNewRoute
  '/lead-sources/new': typeof LeadSourcesNewRoute
  '/leads/new': typeof LeadsNewRoute
  '/meeting-rooms/new': typeof MeetingRoomsNewRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/my-company/new': typeof MyCompanyNewRoute
  '/refusal-reasons/new': typeof RefusalReasonsNewRoute
  '/reports/plan-fact': typeof ReportsPlanFactRoute
  '/reports/target-actions': typeof ReportsTargetActionsRoute
  '/sales-plans/new': typeof SalesPlansNewRoute
  '/signal-types/new': typeof SignalTypesNewRoute
  '/signals/new': typeof SignalsNewRoute
  '/tags/new': typeof TagsNewRoute
  '/target-action-types/new': typeof TargetActionTypesNewRoute
  '/tenders/new': typeof TendersNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/wishlist/new': typeof WishlistNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meetings/$': typeof ApiMeetingsSplatRoute
  '/api/ping/$': typeof ApiPingSplatRoute
  '/changelog/$id/delete': typeof ChangelogIdDeleteRoute
  '/changelog/$id/update': typeof ChangelogIdUpdateRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies/$id/view': typeof CompaniesIdViewRoute
  '/contact-roles/$id/delete': typeof ContactRolesIdDeleteRoute
  '/contact-roles/$id/update': typeof ContactRolesIdUpdateRoute
  '/industries/$id/delete': typeof IndustriesIdDeleteRoute
  '/industries/$id/update': typeof IndustriesIdUpdateRoute
  '/initiatives/$id/delete': typeof InitiativesIdDeleteRoute
  '/initiatives/$id/update': typeof InitiativesIdUpdateRoute
  '/initiatives/$id/view': typeof InitiativesIdViewRoute
  '/lead-sources/$id/delete': typeof LeadSourcesIdDeleteRoute
  '/lead-sources/$id/update': typeof LeadSourcesIdUpdateRoute
  '/leads/$id/delete': typeof LeadsIdDeleteRoute
  '/leads/$id/update': typeof LeadsIdUpdateRoute
  '/leads/$id/view': typeof LeadsIdViewRoute
  '/meeting-rooms/$id/delete': typeof MeetingRoomsIdDeleteRoute
  '/meeting-rooms/$id/update': typeof MeetingRoomsIdUpdateRoute
  '/meetings/$id/copy': typeof MeetingsIdCopyRoute
  '/meetings/$id/delete': typeof MeetingsIdDeleteRoute
  '/meetings/$id/update': typeof MeetingsIdUpdateRoute
  '/meetings/$id/view': typeof MeetingsIdViewRoute
  '/my-company/$id/delete': typeof MyCompanyIdDeleteRoute
  '/my-company/$id/update': typeof MyCompanyIdUpdateRoute
  '/my-company/$id/view': typeof MyCompanyIdViewRoute
  '/refusal-reasons/$id/delete': typeof RefusalReasonsIdDeleteRoute
  '/refusal-reasons/$id/update': typeof RefusalReasonsIdUpdateRoute
  '/sales-plans/$id/delete': typeof SalesPlansIdDeleteRoute
  '/sales-plans/$id/update': typeof SalesPlansIdUpdateRoute
  '/signal-types/$id/delete': typeof SignalTypesIdDeleteRoute
  '/signal-types/$id/update': typeof SignalTypesIdUpdateRoute
  '/signals/$id/delete': typeof SignalsIdDeleteRoute
  '/signals/$id/update': typeof SignalsIdUpdateRoute
  '/signals/$id/view': typeof SignalsIdViewRoute
  '/tags/$id/delete': typeof TagsIdDeleteRoute
  '/tags/$id/update': typeof TagsIdUpdateRoute
  '/target-action-types/$id/delete': typeof TargetActionTypesIdDeleteRoute
  '/target-action-types/$id/update': typeof TargetActionTypesIdUpdateRoute
  '/tenders/$id/delete': typeof TendersIdDeleteRoute
  '/tenders/$id/update': typeof TendersIdUpdateRoute
  '/tenders/$id/view': typeof TendersIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/reset-password': typeof UsersIdResetPasswordRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
  '/wishlist/$id/delete': typeof WishlistIdDeleteRoute
  '/wishlist/$id/update': typeof WishlistIdUpdateRoute
  '/wishlist/$id/view': typeof WishlistIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/contact-roles': typeof ContactRolesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/initiatives': typeof InitiativesRouteWithChildren
  '/lead-sources': typeof LeadSourcesRouteWithChildren
  '/login': typeof LoginRoute
  '/mailing-lists': typeof MailingListsRoute
  '/meeting-rooms': typeof MeetingRoomsRouteWithChildren
  '/meetings': typeof MeetingsRouteWithChildren
  '/my-company': typeof MyCompanyRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/refusal-reasons': typeof RefusalReasonsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales-plans': typeof SalesPlansRouteWithChildren
  '/signal-types': typeof SignalTypesRouteWithChildren
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRoute
  '/tags': typeof TagsRouteWithChildren
  '/target-action-types': typeof TargetActionTypesRouteWithChildren
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRouteWithChildren
  '/changelog/new': typeof ChangelogNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/contact-roles/new': typeof ContactRolesNewRoute
  '/industries/new': typeof IndustriesNewRoute
  '/initiatives/new': typeof InitiativesNewRoute
  '/lead-sources/new': typeof LeadSourcesNewRoute
  '/leads/new': typeof LeadsNewRoute
  '/meeting-rooms/new': typeof MeetingRoomsNewRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/my-company/new': typeof MyCompanyNewRoute
  '/refusal-reasons/new': typeof RefusalReasonsNewRoute
  '/reports_/plan-fact': typeof ReportsPlanFactRoute
  '/reports_/target-actions': typeof ReportsTargetActionsRoute
  '/sales-plans/new': typeof SalesPlansNewRoute
  '/signal-types/new': typeof SignalTypesNewRoute
  '/signals/new': typeof SignalsNewRoute
  '/tags/new': typeof TagsNewRoute
  '/target-action-types/new': typeof TargetActionTypesNewRoute
  '/tenders/new': typeof TendersNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/wishlist/new': typeof WishlistNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/meetings/$': typeof ApiMeetingsSplatRoute
  '/api/ping/$': typeof ApiPingSplatRoute
  '/changelog/$id/delete': typeof ChangelogIdDeleteRoute
  '/changelog/$id/update': typeof ChangelogIdUpdateRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients_/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies_/$id/view': typeof CompaniesIdViewRoute
  '/contact-roles/$id/delete': typeof ContactRolesIdDeleteRoute
  '/contact-roles/$id/update': typeof ContactRolesIdUpdateRoute
  '/industries/$id/delete': typeof IndustriesIdDeleteRoute
  '/industries/$id/update': typeof IndustriesIdUpdateRoute
  '/initiatives/$id/delete': typeof InitiativesIdDeleteRoute
  '/initiatives/$id/update': typeof InitiativesIdUpdateRoute
  '/initiatives/$id/view': typeof InitiativesIdViewRoute
  '/lead-sources/$id/delete': typeof LeadSourcesIdDeleteRoute
  '/lead-sources/$id/update': typeof LeadSourcesIdUpdateRoute
  '/leads/$id/delete': typeof LeadsIdDeleteRoute
  '/leads/$id/update': typeof LeadsIdUpdateRoute
  '/leads_/$id/view': typeof LeadsIdViewRoute
  '/meeting-rooms/$id/delete': typeof MeetingRoomsIdDeleteRoute
  '/meeting-rooms/$id/update': typeof MeetingRoomsIdUpdateRoute
  '/meetings/$id/copy': typeof MeetingsIdCopyRoute
  '/meetings/$id/delete': typeof MeetingsIdDeleteRoute
  '/meetings/$id/update': typeof MeetingsIdUpdateRoute
  '/meetings/$id/view': typeof MeetingsIdViewRoute
  '/my-company/$id/delete': typeof MyCompanyIdDeleteRoute
  '/my-company/$id/update': typeof MyCompanyIdUpdateRoute
  '/my-company_/$id/view': typeof MyCompanyIdViewRoute
  '/refusal-reasons/$id/delete': typeof RefusalReasonsIdDeleteRoute
  '/refusal-reasons/$id/update': typeof RefusalReasonsIdUpdateRoute
  '/sales-plans/$id/delete': typeof SalesPlansIdDeleteRoute
  '/sales-plans/$id/update': typeof SalesPlansIdUpdateRoute
  '/signal-types/$id/delete': typeof SignalTypesIdDeleteRoute
  '/signal-types/$id/update': typeof SignalTypesIdUpdateRoute
  '/signals/$id/delete': typeof SignalsIdDeleteRoute
  '/signals/$id/update': typeof SignalsIdUpdateRoute
  '/signals_/$id/view': typeof SignalsIdViewRoute
  '/tags/$id/delete': typeof TagsIdDeleteRoute
  '/tags/$id/update': typeof TagsIdUpdateRoute
  '/target-action-types/$id/delete': typeof TargetActionTypesIdDeleteRoute
  '/target-action-types/$id/update': typeof TargetActionTypesIdUpdateRoute
  '/tenders/$id/delete': typeof TendersIdDeleteRoute
  '/tenders/$id/update': typeof TendersIdUpdateRoute
  '/tenders_/$id/view': typeof TendersIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos_/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/reset-password': typeof UsersIdResetPasswordRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
  '/wishlist/$id/delete': typeof WishlistIdDeleteRoute
  '/wishlist/$id/update': typeof WishlistIdUpdateRoute
  '/wishlist_/$id/view': typeof WishlistIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/clients'
    | '/companies'
    | '/contact-roles'
    | '/dashboard'
    | '/industries'
    | '/initiatives'
    | '/lead-sources'
    | '/login'
    | '/mailing-lists'
    | '/meeting-rooms'
    | '/meetings'
    | '/my-company'
    | '/preferences'
    | '/refusal-reasons'
    | '/reports'
    | '/sales-plans'
    | '/signal-types'
    | '/signup'
    | '/sources'
    | '/tags'
    | '/target-action-types'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/changelog/new'
    | '/clients/new'
    | '/companies/new'
    | '/contact-roles/new'
    | '/industries/new'
    | '/initiatives/new'
    | '/lead-sources/new'
    | '/leads/new'
    | '/meeting-rooms/new'
    | '/meetings/new'
    | '/my-company/new'
    | '/refusal-reasons/new'
    | '/reports/plan-fact'
    | '/reports/target-actions'
    | '/sales-plans/new'
    | '/signal-types/new'
    | '/signals/new'
    | '/tags/new'
    | '/target-action-types/new'
    | '/tenders/new'
    | '/todos/new'
    | '/users/new'
    | '/wishlist/new'
    | '/api/auth/$'
    | '/api/meetings/$'
    | '/api/ping/$'
    | '/changelog/$id/delete'
    | '/changelog/$id/update'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies/$id/view'
    | '/contact-roles/$id/delete'
    | '/contact-roles/$id/update'
    | '/industries/$id/delete'
    | '/industries/$id/update'
    | '/initiatives/$id/delete'
    | '/initiatives/$id/update'
    | '/initiatives/$id/view'
    | '/lead-sources/$id/delete'
    | '/lead-sources/$id/update'
    | '/leads/$id/delete'
    | '/leads/$id/update'
    | '/leads/$id/view'
    | '/meeting-rooms/$id/delete'
    | '/meeting-rooms/$id/update'
    | '/meetings/$id/copy'
    | '/meetings/$id/delete'
    | '/meetings/$id/update'
    | '/meetings/$id/view'
    | '/my-company/$id/delete'
    | '/my-company/$id/update'
    | '/my-company/$id/view'
    | '/refusal-reasons/$id/delete'
    | '/refusal-reasons/$id/update'
    | '/sales-plans/$id/delete'
    | '/sales-plans/$id/update'
    | '/signal-types/$id/delete'
    | '/signal-types/$id/update'
    | '/signals/$id/delete'
    | '/signals/$id/update'
    | '/signals/$id/view'
    | '/tags/$id/delete'
    | '/tags/$id/update'
    | '/target-action-types/$id/delete'
    | '/target-action-types/$id/update'
    | '/tenders/$id/delete'
    | '/tenders/$id/update'
    | '/tenders/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/reset-password'
    | '/users/$id/unban'
    | '/users/$id/update'
    | '/wishlist/$id/delete'
    | '/wishlist/$id/update'
    | '/wishlist/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/clients'
    | '/companies'
    | '/contact-roles'
    | '/dashboard'
    | '/industries'
    | '/initiatives'
    | '/lead-sources'
    | '/login'
    | '/mailing-lists'
    | '/meeting-rooms'
    | '/meetings'
    | '/my-company'
    | '/preferences'
    | '/refusal-reasons'
    | '/reports'
    | '/sales-plans'
    | '/signal-types'
    | '/signup'
    | '/sources'
    | '/tags'
    | '/target-action-types'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/changelog/new'
    | '/clients/new'
    | '/companies/new'
    | '/contact-roles/new'
    | '/industries/new'
    | '/initiatives/new'
    | '/lead-sources/new'
    | '/leads/new'
    | '/meeting-rooms/new'
    | '/meetings/new'
    | '/my-company/new'
    | '/refusal-reasons/new'
    | '/reports/plan-fact'
    | '/reports/target-actions'
    | '/sales-plans/new'
    | '/signal-types/new'
    | '/signals/new'
    | '/tags/new'
    | '/target-action-types/new'
    | '/tenders/new'
    | '/todos/new'
    | '/users/new'
    | '/wishlist/new'
    | '/api/auth/$'
    | '/api/meetings/$'
    | '/api/ping/$'
    | '/changelog/$id/delete'
    | '/changelog/$id/update'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies/$id/view'
    | '/contact-roles/$id/delete'
    | '/contact-roles/$id/update'
    | '/industries/$id/delete'
    | '/industries/$id/update'
    | '/initiatives/$id/delete'
    | '/initiatives/$id/update'
    | '/initiatives/$id/view'
    | '/lead-sources/$id/delete'
    | '/lead-sources/$id/update'
    | '/leads/$id/delete'
    | '/leads/$id/update'
    | '/leads/$id/view'
    | '/meeting-rooms/$id/delete'
    | '/meeting-rooms/$id/update'
    | '/meetings/$id/copy'
    | '/meetings/$id/delete'
    | '/meetings/$id/update'
    | '/meetings/$id/view'
    | '/my-company/$id/delete'
    | '/my-company/$id/update'
    | '/my-company/$id/view'
    | '/refusal-reasons/$id/delete'
    | '/refusal-reasons/$id/update'
    | '/sales-plans/$id/delete'
    | '/sales-plans/$id/update'
    | '/signal-types/$id/delete'
    | '/signal-types/$id/update'
    | '/signals/$id/delete'
    | '/signals/$id/update'
    | '/signals/$id/view'
    | '/tags/$id/delete'
    | '/tags/$id/update'
    | '/target-action-types/$id/delete'
    | '/target-action-types/$id/update'
    | '/tenders/$id/delete'
    | '/tenders/$id/update'
    | '/tenders/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/reset-password'
    | '/users/$id/unban'
    | '/users/$id/update'
    | '/wishlist/$id/delete'
    | '/wishlist/$id/update'
    | '/wishlist/$id/view'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/clients'
    | '/companies'
    | '/contact-roles'
    | '/dashboard'
    | '/industries'
    | '/initiatives'
    | '/lead-sources'
    | '/login'
    | '/mailing-lists'
    | '/meeting-rooms'
    | '/meetings'
    | '/my-company'
    | '/preferences'
    | '/refusal-reasons'
    | '/reports'
    | '/sales-plans'
    | '/signal-types'
    | '/signup'
    | '/sources'
    | '/tags'
    | '/target-action-types'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/changelog/new'
    | '/clients/new'
    | '/companies/new'
    | '/contact-roles/new'
    | '/industries/new'
    | '/initiatives/new'
    | '/lead-sources/new'
    | '/leads/new'
    | '/meeting-rooms/new'
    | '/meetings/new'
    | '/my-company/new'
    | '/refusal-reasons/new'
    | '/reports_/plan-fact'
    | '/reports_/target-actions'
    | '/sales-plans/new'
    | '/signal-types/new'
    | '/signals/new'
    | '/tags/new'
    | '/target-action-types/new'
    | '/tenders/new'
    | '/todos/new'
    | '/users/new'
    | '/wishlist/new'
    | '/api/auth/$'
    | '/api/meetings/$'
    | '/api/ping/$'
    | '/changelog/$id/delete'
    | '/changelog/$id/update'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients_/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies_/$id/view'
    | '/contact-roles/$id/delete'
    | '/contact-roles/$id/update'
    | '/industries/$id/delete'
    | '/industries/$id/update'
    | '/initiatives/$id/delete'
    | '/initiatives/$id/update'
    | '/initiatives/$id/view'
    | '/lead-sources/$id/delete'
    | '/lead-sources/$id/update'
    | '/leads/$id/delete'
    | '/leads/$id/update'
    | '/leads_/$id/view'
    | '/meeting-rooms/$id/delete'
    | '/meeting-rooms/$id/update'
    | '/meetings/$id/copy'
    | '/meetings/$id/delete'
    | '/meetings/$id/update'
    | '/meetings/$id/view'
    | '/my-company/$id/delete'
    | '/my-company/$id/update'
    | '/my-company_/$id/view'
    | '/refusal-reasons/$id/delete'
    | '/refusal-reasons/$id/update'
    | '/sales-plans/$id/delete'
    | '/sales-plans/$id/update'
    | '/signal-types/$id/delete'
    | '/signal-types/$id/update'
    | '/signals/$id/delete'
    | '/signals/$id/update'
    | '/signals_/$id/view'
    | '/tags/$id/delete'
    | '/tags/$id/update'
    | '/target-action-types/$id/delete'
    | '/target-action-types/$id/update'
    | '/tenders/$id/delete'
    | '/tenders/$id/update'
    | '/tenders_/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos_/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/reset-password'
    | '/users/$id/unban'
    | '/users/$id/update'
    | '/wishlist/$id/delete'
    | '/wishlist/$id/update'
    | '/wishlist_/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactRolesRoute: typeof ContactRolesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  InitiativesRoute: typeof InitiativesRouteWithChildren
  LeadSourcesRoute: typeof LeadSourcesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MailingListsRoute: typeof MailingListsRoute
  MeetingRoomsRoute: typeof MeetingRoomsRouteWithChildren
  MeetingsRoute: typeof MeetingsRouteWithChildren
  MyCompanyRoute: typeof MyCompanyRouteWithChildren
  PreferencesRoute: typeof PreferencesRoute
  RefusalReasonsRoute: typeof RefusalReasonsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SalesPlansRoute: typeof SalesPlansRouteWithChildren
  SignalTypesRoute: typeof SignalTypesRouteWithChildren
  SignupRoute: typeof SignupRoute
  SourcesRoute: typeof SourcesRoute
  TagsRoute: typeof TagsRouteWithChildren
  TargetActionTypesRoute: typeof TargetActionTypesRouteWithChildren
  TodosRoute: typeof TodosRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  WishlistRoute: typeof WishlistRouteWithChildren
  LeadsNewRoute: typeof LeadsNewRoute
  ReportsPlanFactRoute: typeof ReportsPlanFactRoute
  ReportsTargetActionsRoute: typeof ReportsTargetActionsRoute
  SignalsNewRoute: typeof SignalsNewRoute
  TendersNewRoute: typeof TendersNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMeetingsSplatRoute: typeof ApiMeetingsSplatRoute
  ApiPingSplatRoute: typeof ApiPingSplatRoute
  ClientsIdViewRoute: typeof ClientsIdViewRoute
  CompaniesIdViewRoute: typeof CompaniesIdViewRoute
  LeadsIdDeleteRoute: typeof LeadsIdDeleteRoute
  LeadsIdUpdateRoute: typeof LeadsIdUpdateRoute
  LeadsIdViewRoute: typeof LeadsIdViewRoute
  MyCompanyIdViewRoute: typeof MyCompanyIdViewRoute
  SignalsIdDeleteRoute: typeof SignalsIdDeleteRoute
  SignalsIdUpdateRoute: typeof SignalsIdUpdateRoute
  SignalsIdViewRoute: typeof SignalsIdViewRoute
  TendersIdDeleteRoute: typeof TendersIdDeleteRoute
  TendersIdUpdateRoute: typeof TendersIdUpdateRoute
  TendersIdViewRoute: typeof TendersIdViewRoute
  TodosIdViewRoute: typeof TodosIdViewRoute
  WishlistIdViewRoute: typeof WishlistIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-action-types': {
      id: '/target-action-types'
      path: '/target-action-types'
      fullPath: '/target-action-types'
      preLoaderRoute: typeof TargetActionTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-types': {
      id: '/signal-types'
      path: '/signal-types'
      fullPath: '/signal-types'
      preLoaderRoute: typeof SignalTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-plans': {
      id: '/sales-plans'
      path: '/sales-plans'
      fullPath: '/sales-plans'
      preLoaderRoute: typeof SalesPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refusal-reasons': {
      id: '/refusal-reasons'
      path: '/refusal-reasons'
      fullPath: '/refusal-reasons'
      preLoaderRoute: typeof RefusalReasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-company': {
      id: '/my-company'
      path: '/my-company'
      fullPath: '/my-company'
      preLoaderRoute: typeof MyCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-rooms': {
      id: '/meeting-rooms'
      path: '/meeting-rooms'
      fullPath: '/meeting-rooms'
      preLoaderRoute: typeof MeetingRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailing-lists': {
      id: '/mailing-lists'
      path: '/mailing-lists'
      fullPath: '/mailing-lists'
      preLoaderRoute: typeof MailingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-sources': {
      id: '/lead-sources'
      path: '/lead-sources'
      fullPath: '/lead-sources'
      preLoaderRoute: typeof LeadSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-roles': {
      id: '/contact-roles'
      path: '/contact-roles'
      fullPath: '/contact-roles'
      preLoaderRoute: typeof ContactRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/new': {
      id: '/wishlist/new'
      path: '/new'
      fullPath: '/wishlist/new'
      preLoaderRoute: typeof WishlistNewRouteImport
      parentRoute: typeof WishlistRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof TodosRoute
    }
    '/tenders/new': {
      id: '/tenders/new'
      path: '/tenders/new'
      fullPath: '/tenders/new'
      preLoaderRoute: typeof TendersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-action-types/new': {
      id: '/target-action-types/new'
      path: '/new'
      fullPath: '/target-action-types/new'
      preLoaderRoute: typeof TargetActionTypesNewRouteImport
      parentRoute: typeof TargetActionTypesRoute
    }
    '/tags/new': {
      id: '/tags/new'
      path: '/new'
      fullPath: '/tags/new'
      preLoaderRoute: typeof TagsNewRouteImport
      parentRoute: typeof TagsRoute
    }
    '/signals/new': {
      id: '/signals/new'
      path: '/signals/new'
      fullPath: '/signals/new'
      preLoaderRoute: typeof SignalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-types/new': {
      id: '/signal-types/new'
      path: '/new'
      fullPath: '/signal-types/new'
      preLoaderRoute: typeof SignalTypesNewRouteImport
      parentRoute: typeof SignalTypesRoute
    }
    '/sales-plans/new': {
      id: '/sales-plans/new'
      path: '/new'
      fullPath: '/sales-plans/new'
      preLoaderRoute: typeof SalesPlansNewRouteImport
      parentRoute: typeof SalesPlansRoute
    }
    '/reports_/target-actions': {
      id: '/reports_/target-actions'
      path: '/reports/target-actions'
      fullPath: '/reports/target-actions'
      preLoaderRoute: typeof ReportsTargetActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/plan-fact': {
      id: '/reports_/plan-fact'
      path: '/reports/plan-fact'
      fullPath: '/reports/plan-fact'
      preLoaderRoute: typeof ReportsPlanFactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refusal-reasons/new': {
      id: '/refusal-reasons/new'
      path: '/new'
      fullPath: '/refusal-reasons/new'
      preLoaderRoute: typeof RefusalReasonsNewRouteImport
      parentRoute: typeof RefusalReasonsRoute
    }
    '/my-company/new': {
      id: '/my-company/new'
      path: '/new'
      fullPath: '/my-company/new'
      preLoaderRoute: typeof MyCompanyNewRouteImport
      parentRoute: typeof MyCompanyRoute
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meeting-rooms/new': {
      id: '/meeting-rooms/new'
      path: '/new'
      fullPath: '/meeting-rooms/new'
      preLoaderRoute: typeof MeetingRoomsNewRouteImport
      parentRoute: typeof MeetingRoomsRoute
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-sources/new': {
      id: '/lead-sources/new'
      path: '/new'
      fullPath: '/lead-sources/new'
      preLoaderRoute: typeof LeadSourcesNewRouteImport
      parentRoute: typeof LeadSourcesRoute
    }
    '/initiatives/new': {
      id: '/initiatives/new'
      path: '/new'
      fullPath: '/initiatives/new'
      preLoaderRoute: typeof InitiativesNewRouteImport
      parentRoute: typeof InitiativesRoute
    }
    '/industries/new': {
      id: '/industries/new'
      path: '/new'
      fullPath: '/industries/new'
      preLoaderRoute: typeof IndustriesNewRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/contact-roles/new': {
      id: '/contact-roles/new'
      path: '/new'
      fullPath: '/contact-roles/new'
      preLoaderRoute: typeof ContactRolesNewRouteImport
      parentRoute: typeof ContactRolesRoute
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/changelog/new': {
      id: '/changelog/new'
      path: '/new'
      fullPath: '/changelog/new'
      preLoaderRoute: typeof ChangelogNewRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/wishlist_/$id/view': {
      id: '/wishlist_/$id/view'
      path: '/wishlist/$id/view'
      fullPath: '/wishlist/$id/view'
      preLoaderRoute: typeof WishlistIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/$id/update': {
      id: '/wishlist/$id/update'
      path: '/$id/update'
      fullPath: '/wishlist/$id/update'
      preLoaderRoute: typeof WishlistIdUpdateRouteImport
      parentRoute: typeof WishlistRoute
    }
    '/wishlist/$id/delete': {
      id: '/wishlist/$id/delete'
      path: '/$id/delete'
      fullPath: '/wishlist/$id/delete'
      preLoaderRoute: typeof WishlistIdDeleteRouteImport
      parentRoute: typeof WishlistRoute
    }
    '/users/$id/update': {
      id: '/users/$id/update'
      path: '/$id/update'
      fullPath: '/users/$id/update'
      preLoaderRoute: typeof UsersIdUpdateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/unban': {
      id: '/users/$id/unban'
      path: '/$id/unban'
      fullPath: '/users/$id/unban'
      preLoaderRoute: typeof UsersIdUnbanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/reset-password': {
      id: '/users/$id/reset-password'
      path: '/$id/reset-password'
      fullPath: '/users/$id/reset-password'
      preLoaderRoute: typeof UsersIdResetPasswordRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/delete': {
      id: '/users/$id/delete'
      path: '/$id/delete'
      fullPath: '/users/$id/delete'
      preLoaderRoute: typeof UsersIdDeleteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/ban': {
      id: '/users/$id/ban'
      path: '/$id/ban'
      fullPath: '/users/$id/ban'
      preLoaderRoute: typeof UsersIdBanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/todos_/$id/view': {
      id: '/todos_/$id/view'
      path: '/todos/$id/view'
      fullPath: '/todos/$id/view'
      preLoaderRoute: typeof TodosIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/update': {
      id: '/todos/$id/update'
      path: '/$id/update'
      fullPath: '/todos/$id/update'
      preLoaderRoute: typeof TodosIdUpdateRouteImport
      parentRoute: typeof TodosRoute
    }
    '/todos/$id/delete': {
      id: '/todos/$id/delete'
      path: '/$id/delete'
      fullPath: '/todos/$id/delete'
      preLoaderRoute: typeof TodosIdDeleteRouteImport
      parentRoute: typeof TodosRoute
    }
    '/tenders_/$id/view': {
      id: '/tenders_/$id/view'
      path: '/tenders/$id/view'
      fullPath: '/tenders/$id/view'
      preLoaderRoute: typeof TendersIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/$id/update': {
      id: '/tenders/$id/update'
      path: '/tenders/$id/update'
      fullPath: '/tenders/$id/update'
      preLoaderRoute: typeof TendersIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/$id/delete': {
      id: '/tenders/$id/delete'
      path: '/tenders/$id/delete'
      fullPath: '/tenders/$id/delete'
      preLoaderRoute: typeof TendersIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-action-types/$id/update': {
      id: '/target-action-types/$id/update'
      path: '/$id/update'
      fullPath: '/target-action-types/$id/update'
      preLoaderRoute: typeof TargetActionTypesIdUpdateRouteImport
      parentRoute: typeof TargetActionTypesRoute
    }
    '/target-action-types/$id/delete': {
      id: '/target-action-types/$id/delete'
      path: '/$id/delete'
      fullPath: '/target-action-types/$id/delete'
      preLoaderRoute: typeof TargetActionTypesIdDeleteRouteImport
      parentRoute: typeof TargetActionTypesRoute
    }
    '/tags/$id/update': {
      id: '/tags/$id/update'
      path: '/$id/update'
      fullPath: '/tags/$id/update'
      preLoaderRoute: typeof TagsIdUpdateRouteImport
      parentRoute: typeof TagsRoute
    }
    '/tags/$id/delete': {
      id: '/tags/$id/delete'
      path: '/$id/delete'
      fullPath: '/tags/$id/delete'
      preLoaderRoute: typeof TagsIdDeleteRouteImport
      parentRoute: typeof TagsRoute
    }
    '/signals_/$id/view': {
      id: '/signals_/$id/view'
      path: '/signals/$id/view'
      fullPath: '/signals/$id/view'
      preLoaderRoute: typeof SignalsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$id/update': {
      id: '/signals/$id/update'
      path: '/signals/$id/update'
      fullPath: '/signals/$id/update'
      preLoaderRoute: typeof SignalsIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$id/delete': {
      id: '/signals/$id/delete'
      path: '/signals/$id/delete'
      fullPath: '/signals/$id/delete'
      preLoaderRoute: typeof SignalsIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-types/$id/update': {
      id: '/signal-types/$id/update'
      path: '/$id/update'
      fullPath: '/signal-types/$id/update'
      preLoaderRoute: typeof SignalTypesIdUpdateRouteImport
      parentRoute: typeof SignalTypesRoute
    }
    '/signal-types/$id/delete': {
      id: '/signal-types/$id/delete'
      path: '/$id/delete'
      fullPath: '/signal-types/$id/delete'
      preLoaderRoute: typeof SignalTypesIdDeleteRouteImport
      parentRoute: typeof SignalTypesRoute
    }
    '/sales-plans/$id/update': {
      id: '/sales-plans/$id/update'
      path: '/$id/update'
      fullPath: '/sales-plans/$id/update'
      preLoaderRoute: typeof SalesPlansIdUpdateRouteImport
      parentRoute: typeof SalesPlansRoute
    }
    '/sales-plans/$id/delete': {
      id: '/sales-plans/$id/delete'
      path: '/$id/delete'
      fullPath: '/sales-plans/$id/delete'
      preLoaderRoute: typeof SalesPlansIdDeleteRouteImport
      parentRoute: typeof SalesPlansRoute
    }
    '/refusal-reasons/$id/update': {
      id: '/refusal-reasons/$id/update'
      path: '/$id/update'
      fullPath: '/refusal-reasons/$id/update'
      preLoaderRoute: typeof RefusalReasonsIdUpdateRouteImport
      parentRoute: typeof RefusalReasonsRoute
    }
    '/refusal-reasons/$id/delete': {
      id: '/refusal-reasons/$id/delete'
      path: '/$id/delete'
      fullPath: '/refusal-reasons/$id/delete'
      preLoaderRoute: typeof RefusalReasonsIdDeleteRouteImport
      parentRoute: typeof RefusalReasonsRoute
    }
    '/my-company_/$id/view': {
      id: '/my-company_/$id/view'
      path: '/my-company/$id/view'
      fullPath: '/my-company/$id/view'
      preLoaderRoute: typeof MyCompanyIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-company/$id/update': {
      id: '/my-company/$id/update'
      path: '/$id/update'
      fullPath: '/my-company/$id/update'
      preLoaderRoute: typeof MyCompanyIdUpdateRouteImport
      parentRoute: typeof MyCompanyRoute
    }
    '/my-company/$id/delete': {
      id: '/my-company/$id/delete'
      path: '/$id/delete'
      fullPath: '/my-company/$id/delete'
      preLoaderRoute: typeof MyCompanyIdDeleteRouteImport
      parentRoute: typeof MyCompanyRoute
    }
    '/meetings/$id/view': {
      id: '/meetings/$id/view'
      path: '/$id/view'
      fullPath: '/meetings/$id/view'
      preLoaderRoute: typeof MeetingsIdViewRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/$id/update': {
      id: '/meetings/$id/update'
      path: '/$id/update'
      fullPath: '/meetings/$id/update'
      preLoaderRoute: typeof MeetingsIdUpdateRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/$id/delete': {
      id: '/meetings/$id/delete'
      path: '/$id/delete'
      fullPath: '/meetings/$id/delete'
      preLoaderRoute: typeof MeetingsIdDeleteRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/$id/copy': {
      id: '/meetings/$id/copy'
      path: '/$id/copy'
      fullPath: '/meetings/$id/copy'
      preLoaderRoute: typeof MeetingsIdCopyRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meeting-rooms/$id/update': {
      id: '/meeting-rooms/$id/update'
      path: '/$id/update'
      fullPath: '/meeting-rooms/$id/update'
      preLoaderRoute: typeof MeetingRoomsIdUpdateRouteImport
      parentRoute: typeof MeetingRoomsRoute
    }
    '/meeting-rooms/$id/delete': {
      id: '/meeting-rooms/$id/delete'
      path: '/$id/delete'
      fullPath: '/meeting-rooms/$id/delete'
      preLoaderRoute: typeof MeetingRoomsIdDeleteRouteImport
      parentRoute: typeof MeetingRoomsRoute
    }
    '/leads_/$id/view': {
      id: '/leads_/$id/view'
      path: '/leads/$id/view'
      fullPath: '/leads/$id/view'
      preLoaderRoute: typeof LeadsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id/update': {
      id: '/leads/$id/update'
      path: '/leads/$id/update'
      fullPath: '/leads/$id/update'
      preLoaderRoute: typeof LeadsIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id/delete': {
      id: '/leads/$id/delete'
      path: '/leads/$id/delete'
      fullPath: '/leads/$id/delete'
      preLoaderRoute: typeof LeadsIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-sources/$id/update': {
      id: '/lead-sources/$id/update'
      path: '/$id/update'
      fullPath: '/lead-sources/$id/update'
      preLoaderRoute: typeof LeadSourcesIdUpdateRouteImport
      parentRoute: typeof LeadSourcesRoute
    }
    '/lead-sources/$id/delete': {
      id: '/lead-sources/$id/delete'
      path: '/$id/delete'
      fullPath: '/lead-sources/$id/delete'
      preLoaderRoute: typeof LeadSourcesIdDeleteRouteImport
      parentRoute: typeof LeadSourcesRoute
    }
    '/initiatives/$id/view': {
      id: '/initiatives/$id/view'
      path: '/$id/view'
      fullPath: '/initiatives/$id/view'
      preLoaderRoute: typeof InitiativesIdViewRouteImport
      parentRoute: typeof InitiativesRoute
    }
    '/initiatives/$id/update': {
      id: '/initiatives/$id/update'
      path: '/$id/update'
      fullPath: '/initiatives/$id/update'
      preLoaderRoute: typeof InitiativesIdUpdateRouteImport
      parentRoute: typeof InitiativesRoute
    }
    '/initiatives/$id/delete': {
      id: '/initiatives/$id/delete'
      path: '/$id/delete'
      fullPath: '/initiatives/$id/delete'
      preLoaderRoute: typeof InitiativesIdDeleteRouteImport
      parentRoute: typeof InitiativesRoute
    }
    '/industries/$id/update': {
      id: '/industries/$id/update'
      path: '/$id/update'
      fullPath: '/industries/$id/update'
      preLoaderRoute: typeof IndustriesIdUpdateRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/$id/delete': {
      id: '/industries/$id/delete'
      path: '/$id/delete'
      fullPath: '/industries/$id/delete'
      preLoaderRoute: typeof IndustriesIdDeleteRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/contact-roles/$id/update': {
      id: '/contact-roles/$id/update'
      path: '/$id/update'
      fullPath: '/contact-roles/$id/update'
      preLoaderRoute: typeof ContactRolesIdUpdateRouteImport
      parentRoute: typeof ContactRolesRoute
    }
    '/contact-roles/$id/delete': {
      id: '/contact-roles/$id/delete'
      path: '/$id/delete'
      fullPath: '/contact-roles/$id/delete'
      preLoaderRoute: typeof ContactRolesIdDeleteRouteImport
      parentRoute: typeof ContactRolesRoute
    }
    '/companies_/$id/view': {
      id: '/companies_/$id/view'
      path: '/companies/$id/view'
      fullPath: '/companies/$id/view'
      preLoaderRoute: typeof CompaniesIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id/update': {
      id: '/companies/$id/update'
      path: '/$id/update'
      fullPath: '/companies/$id/update'
      preLoaderRoute: typeof CompaniesIdUpdateRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$id/delete': {
      id: '/companies/$id/delete'
      path: '/$id/delete'
      fullPath: '/companies/$id/delete'
      preLoaderRoute: typeof CompaniesIdDeleteRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/clients_/$id/view': {
      id: '/clients_/$id/view'
      path: '/clients/$id/view'
      fullPath: '/clients/$id/view'
      preLoaderRoute: typeof ClientsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id/update': {
      id: '/clients/$id/update'
      path: '/$id/update'
      fullPath: '/clients/$id/update'
      preLoaderRoute: typeof ClientsIdUpdateRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$id/delete': {
      id: '/clients/$id/delete'
      path: '/$id/delete'
      fullPath: '/clients/$id/delete'
      preLoaderRoute: typeof ClientsIdDeleteRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/changelog/$id/update': {
      id: '/changelog/$id/update'
      path: '/$id/update'
      fullPath: '/changelog/$id/update'
      preLoaderRoute: typeof ChangelogIdUpdateRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/changelog/$id/delete': {
      id: '/changelog/$id/delete'
      path: '/$id/delete'
      fullPath: '/changelog/$id/delete'
      preLoaderRoute: typeof ChangelogIdDeleteRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/api/ping/$': {
      id: '/api/ping/$'
      path: '/api/ping/$'
      fullPath: '/api/ping/$'
      preLoaderRoute: typeof ApiPingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$': {
      id: '/api/meetings/$'
      path: '/api/meetings/$'
      fullPath: '/api/meetings/$'
      preLoaderRoute: typeof ApiMeetingsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogNewRoute: typeof ChangelogNewRoute
  ChangelogIdDeleteRoute: typeof ChangelogIdDeleteRoute
  ChangelogIdUpdateRoute: typeof ChangelogIdUpdateRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogNewRoute: ChangelogNewRoute,
  ChangelogIdDeleteRoute: ChangelogIdDeleteRoute,
  ChangelogIdUpdateRoute: ChangelogIdUpdateRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface ClientsRouteChildren {
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIdDeleteRoute: typeof ClientsIdDeleteRoute
  ClientsIdUpdateRoute: typeof ClientsIdUpdateRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsNewRoute: ClientsNewRoute,
  ClientsIdDeleteRoute: ClientsIdDeleteRoute,
  ClientsIdUpdateRoute: ClientsIdUpdateRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CompaniesRouteChildren {
  CompaniesNewRoute: typeof CompaniesNewRoute
  CompaniesIdDeleteRoute: typeof CompaniesIdDeleteRoute
  CompaniesIdUpdateRoute: typeof CompaniesIdUpdateRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesNewRoute: CompaniesNewRoute,
  CompaniesIdDeleteRoute: CompaniesIdDeleteRoute,
  CompaniesIdUpdateRoute: CompaniesIdUpdateRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ContactRolesRouteChildren {
  ContactRolesNewRoute: typeof ContactRolesNewRoute
  ContactRolesIdDeleteRoute: typeof ContactRolesIdDeleteRoute
  ContactRolesIdUpdateRoute: typeof ContactRolesIdUpdateRoute
}

const ContactRolesRouteChildren: ContactRolesRouteChildren = {
  ContactRolesNewRoute: ContactRolesNewRoute,
  ContactRolesIdDeleteRoute: ContactRolesIdDeleteRoute,
  ContactRolesIdUpdateRoute: ContactRolesIdUpdateRoute,
}

const ContactRolesRouteWithChildren = ContactRolesRoute._addFileChildren(
  ContactRolesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesNewRoute: typeof IndustriesNewRoute
  IndustriesIdDeleteRoute: typeof IndustriesIdDeleteRoute
  IndustriesIdUpdateRoute: typeof IndustriesIdUpdateRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesNewRoute: IndustriesNewRoute,
  IndustriesIdDeleteRoute: IndustriesIdDeleteRoute,
  IndustriesIdUpdateRoute: IndustriesIdUpdateRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface InitiativesRouteChildren {
  InitiativesNewRoute: typeof InitiativesNewRoute
  InitiativesIdDeleteRoute: typeof InitiativesIdDeleteRoute
  InitiativesIdUpdateRoute: typeof InitiativesIdUpdateRoute
  InitiativesIdViewRoute: typeof InitiativesIdViewRoute
}

const InitiativesRouteChildren: InitiativesRouteChildren = {
  InitiativesNewRoute: InitiativesNewRoute,
  InitiativesIdDeleteRoute: InitiativesIdDeleteRoute,
  InitiativesIdUpdateRoute: InitiativesIdUpdateRoute,
  InitiativesIdViewRoute: InitiativesIdViewRoute,
}

const InitiativesRouteWithChildren = InitiativesRoute._addFileChildren(
  InitiativesRouteChildren,
)

interface LeadSourcesRouteChildren {
  LeadSourcesNewRoute: typeof LeadSourcesNewRoute
  LeadSourcesIdDeleteRoute: typeof LeadSourcesIdDeleteRoute
  LeadSourcesIdUpdateRoute: typeof LeadSourcesIdUpdateRoute
}

const LeadSourcesRouteChildren: LeadSourcesRouteChildren = {
  LeadSourcesNewRoute: LeadSourcesNewRoute,
  LeadSourcesIdDeleteRoute: LeadSourcesIdDeleteRoute,
  LeadSourcesIdUpdateRoute: LeadSourcesIdUpdateRoute,
}

const LeadSourcesRouteWithChildren = LeadSourcesRoute._addFileChildren(
  LeadSourcesRouteChildren,
)

interface MeetingRoomsRouteChildren {
  MeetingRoomsNewRoute: typeof MeetingRoomsNewRoute
  MeetingRoomsIdDeleteRoute: typeof MeetingRoomsIdDeleteRoute
  MeetingRoomsIdUpdateRoute: typeof MeetingRoomsIdUpdateRoute
}

const MeetingRoomsRouteChildren: MeetingRoomsRouteChildren = {
  MeetingRoomsNewRoute: MeetingRoomsNewRoute,
  MeetingRoomsIdDeleteRoute: MeetingRoomsIdDeleteRoute,
  MeetingRoomsIdUpdateRoute: MeetingRoomsIdUpdateRoute,
}

const MeetingRoomsRouteWithChildren = MeetingRoomsRoute._addFileChildren(
  MeetingRoomsRouteChildren,
)

interface MeetingsRouteChildren {
  MeetingsNewRoute: typeof MeetingsNewRoute
  MeetingsIdCopyRoute: typeof MeetingsIdCopyRoute
  MeetingsIdDeleteRoute: typeof MeetingsIdDeleteRoute
  MeetingsIdUpdateRoute: typeof MeetingsIdUpdateRoute
  MeetingsIdViewRoute: typeof MeetingsIdViewRoute
}

const MeetingsRouteChildren: MeetingsRouteChildren = {
  MeetingsNewRoute: MeetingsNewRoute,
  MeetingsIdCopyRoute: MeetingsIdCopyRoute,
  MeetingsIdDeleteRoute: MeetingsIdDeleteRoute,
  MeetingsIdUpdateRoute: MeetingsIdUpdateRoute,
  MeetingsIdViewRoute: MeetingsIdViewRoute,
}

const MeetingsRouteWithChildren = MeetingsRoute._addFileChildren(
  MeetingsRouteChildren,
)

interface MyCompanyRouteChildren {
  MyCompanyNewRoute: typeof MyCompanyNewRoute
  MyCompanyIdDeleteRoute: typeof MyCompanyIdDeleteRoute
  MyCompanyIdUpdateRoute: typeof MyCompanyIdUpdateRoute
}

const MyCompanyRouteChildren: MyCompanyRouteChildren = {
  MyCompanyNewRoute: MyCompanyNewRoute,
  MyCompanyIdDeleteRoute: MyCompanyIdDeleteRoute,
  MyCompanyIdUpdateRoute: MyCompanyIdUpdateRoute,
}

const MyCompanyRouteWithChildren = MyCompanyRoute._addFileChildren(
  MyCompanyRouteChildren,
)

interface RefusalReasonsRouteChildren {
  RefusalReasonsNewRoute: typeof RefusalReasonsNewRoute
  RefusalReasonsIdDeleteRoute: typeof RefusalReasonsIdDeleteRoute
  RefusalReasonsIdUpdateRoute: typeof RefusalReasonsIdUpdateRoute
}

const RefusalReasonsRouteChildren: RefusalReasonsRouteChildren = {
  RefusalReasonsNewRoute: RefusalReasonsNewRoute,
  RefusalReasonsIdDeleteRoute: RefusalReasonsIdDeleteRoute,
  RefusalReasonsIdUpdateRoute: RefusalReasonsIdUpdateRoute,
}

const RefusalReasonsRouteWithChildren = RefusalReasonsRoute._addFileChildren(
  RefusalReasonsRouteChildren,
)

interface SalesPlansRouteChildren {
  SalesPlansNewRoute: typeof SalesPlansNewRoute
  SalesPlansIdDeleteRoute: typeof SalesPlansIdDeleteRoute
  SalesPlansIdUpdateRoute: typeof SalesPlansIdUpdateRoute
}

const SalesPlansRouteChildren: SalesPlansRouteChildren = {
  SalesPlansNewRoute: SalesPlansNewRoute,
  SalesPlansIdDeleteRoute: SalesPlansIdDeleteRoute,
  SalesPlansIdUpdateRoute: SalesPlansIdUpdateRoute,
}

const SalesPlansRouteWithChildren = SalesPlansRoute._addFileChildren(
  SalesPlansRouteChildren,
)

interface SignalTypesRouteChildren {
  SignalTypesNewRoute: typeof SignalTypesNewRoute
  SignalTypesIdDeleteRoute: typeof SignalTypesIdDeleteRoute
  SignalTypesIdUpdateRoute: typeof SignalTypesIdUpdateRoute
}

const SignalTypesRouteChildren: SignalTypesRouteChildren = {
  SignalTypesNewRoute: SignalTypesNewRoute,
  SignalTypesIdDeleteRoute: SignalTypesIdDeleteRoute,
  SignalTypesIdUpdateRoute: SignalTypesIdUpdateRoute,
}

const SignalTypesRouteWithChildren = SignalTypesRoute._addFileChildren(
  SignalTypesRouteChildren,
)

interface TagsRouteChildren {
  TagsNewRoute: typeof TagsNewRoute
  TagsIdDeleteRoute: typeof TagsIdDeleteRoute
  TagsIdUpdateRoute: typeof TagsIdUpdateRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsNewRoute: TagsNewRoute,
  TagsIdDeleteRoute: TagsIdDeleteRoute,
  TagsIdUpdateRoute: TagsIdUpdateRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

interface TargetActionTypesRouteChildren {
  TargetActionTypesNewRoute: typeof TargetActionTypesNewRoute
  TargetActionTypesIdDeleteRoute: typeof TargetActionTypesIdDeleteRoute
  TargetActionTypesIdUpdateRoute: typeof TargetActionTypesIdUpdateRoute
}

const TargetActionTypesRouteChildren: TargetActionTypesRouteChildren = {
  TargetActionTypesNewRoute: TargetActionTypesNewRoute,
  TargetActionTypesIdDeleteRoute: TargetActionTypesIdDeleteRoute,
  TargetActionTypesIdUpdateRoute: TargetActionTypesIdUpdateRoute,
}

const TargetActionTypesRouteWithChildren =
  TargetActionTypesRoute._addFileChildren(TargetActionTypesRouteChildren)

interface TodosRouteChildren {
  TodosNewRoute: typeof TodosNewRoute
  TodosIdDeleteRoute: typeof TodosIdDeleteRoute
  TodosIdUpdateRoute: typeof TodosIdUpdateRoute
}

const TodosRouteChildren: TodosRouteChildren = {
  TodosNewRoute: TodosNewRoute,
  TodosIdDeleteRoute: TodosIdDeleteRoute,
  TodosIdUpdateRoute: TodosIdUpdateRoute,
}

const TodosRouteWithChildren = TodosRoute._addFileChildren(TodosRouteChildren)

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
  UsersIdBanRoute: typeof UsersIdBanRoute
  UsersIdDeleteRoute: typeof UsersIdDeleteRoute
  UsersIdResetPasswordRoute: typeof UsersIdResetPasswordRoute
  UsersIdUnbanRoute: typeof UsersIdUnbanRoute
  UsersIdUpdateRoute: typeof UsersIdUpdateRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
  UsersIdBanRoute: UsersIdBanRoute,
  UsersIdDeleteRoute: UsersIdDeleteRoute,
  UsersIdResetPasswordRoute: UsersIdResetPasswordRoute,
  UsersIdUnbanRoute: UsersIdUnbanRoute,
  UsersIdUpdateRoute: UsersIdUpdateRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface WishlistRouteChildren {
  WishlistNewRoute: typeof WishlistNewRoute
  WishlistIdDeleteRoute: typeof WishlistIdDeleteRoute
  WishlistIdUpdateRoute: typeof WishlistIdUpdateRoute
}

const WishlistRouteChildren: WishlistRouteChildren = {
  WishlistNewRoute: WishlistNewRoute,
  WishlistIdDeleteRoute: WishlistIdDeleteRoute,
  WishlistIdUpdateRoute: WishlistIdUpdateRoute,
}

const WishlistRouteWithChildren = WishlistRoute._addFileChildren(
  WishlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactRolesRoute: ContactRolesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  InitiativesRoute: InitiativesRouteWithChildren,
  LeadSourcesRoute: LeadSourcesRouteWithChildren,
  LoginRoute: LoginRoute,
  MailingListsRoute: MailingListsRoute,
  MeetingRoomsRoute: MeetingRoomsRouteWithChildren,
  MeetingsRoute: MeetingsRouteWithChildren,
  MyCompanyRoute: MyCompanyRouteWithChildren,
  PreferencesRoute: PreferencesRoute,
  RefusalReasonsRoute: RefusalReasonsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SalesPlansRoute: SalesPlansRouteWithChildren,
  SignalTypesRoute: SignalTypesRouteWithChildren,
  SignupRoute: SignupRoute,
  SourcesRoute: SourcesRoute,
  TagsRoute: TagsRouteWithChildren,
  TargetActionTypesRoute: TargetActionTypesRouteWithChildren,
  TodosRoute: TodosRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  WishlistRoute: WishlistRouteWithChildren,
  LeadsNewRoute: LeadsNewRoute,
  ReportsPlanFactRoute: ReportsPlanFactRoute,
  ReportsTargetActionsRoute: ReportsTargetActionsRoute,
  SignalsNewRoute: SignalsNewRoute,
  TendersNewRoute: TendersNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMeetingsSplatRoute: ApiMeetingsSplatRoute,
  ApiPingSplatRoute: ApiPingSplatRoute,
  ClientsIdViewRoute: ClientsIdViewRoute,
  CompaniesIdViewRoute: CompaniesIdViewRoute,
  LeadsIdDeleteRoute: LeadsIdDeleteRoute,
  LeadsIdUpdateRoute: LeadsIdUpdateRoute,
  LeadsIdViewRoute: LeadsIdViewRoute,
  MyCompanyIdViewRoute: MyCompanyIdViewRoute,
  SignalsIdDeleteRoute: SignalsIdDeleteRoute,
  SignalsIdUpdateRoute: SignalsIdUpdateRoute,
  SignalsIdViewRoute: SignalsIdViewRoute,
  TendersIdDeleteRoute: TendersIdDeleteRoute,
  TendersIdUpdateRoute: TendersIdUpdateRoute,
  TendersIdViewRoute: TendersIdViewRoute,
  TodosIdViewRoute: TodosIdViewRoute,
  WishlistIdViewRoute: WishlistIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
