/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as TodosNewRouteImport } from './routes/todos.new'
import { Route as DepartmentsNewRouteImport } from './routes/departments.new'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as UsersIdUpdateRouteImport } from './routes/users.$id.update'
import { Route as UsersIdUnbanRouteImport } from './routes/users.$id.unban'
import { Route as UsersIdDeleteRouteImport } from './routes/users.$id.delete'
import { Route as UsersIdBanRouteImport } from './routes/users.$id.ban'
import { Route as TodosIdViewRouteImport } from './routes/todos_.$id.view'
import { Route as TodosIdUpdateRouteImport } from './routes/todos.$id.update'
import { Route as TodosIdDeleteRouteImport } from './routes/todos.$id.delete'
import { Route as DepartmentsIdViewRouteImport } from './routes/departments_.$id.view'
import { Route as DepartmentsIdUpdateRouteImport } from './routes/departments.$id.update'
import { Route as DepartmentsIdDeleteRouteImport } from './routes/departments.$id.delete'
import { Route as CompaniesIdViewRouteImport } from './routes/companies_.$id.view'
import { Route as CompaniesIdUpdateRouteImport } from './routes/companies.$id.update'
import { Route as CompaniesIdDeleteRouteImport } from './routes/companies.$id.delete'
import { Route as ClientsIdViewRouteImport } from './routes/clients_.$id.view'
import { Route as ClientsIdUpdateRouteImport } from './routes/clients.$id.update'
import { Route as ClientsIdDeleteRouteImport } from './routes/clients.$id.delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TodosRoute,
} as any)
const DepartmentsNewRoute = DepartmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DepartmentsRoute,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const UsersIdUpdateRoute = UsersIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdUnbanRoute = UsersIdUnbanRouteImport.update({
  id: '/$id/unban',
  path: '/$id/unban',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdDeleteRoute = UsersIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdBanRoute = UsersIdBanRouteImport.update({
  id: '/$id/ban',
  path: '/$id/ban',
  getParentRoute: () => UsersRoute,
} as any)
const TodosIdViewRoute = TodosIdViewRouteImport.update({
  id: '/todos_/$id/view',
  path: '/todos/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdUpdateRoute = TodosIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => TodosRoute,
} as any)
const TodosIdDeleteRoute = TodosIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => TodosRoute,
} as any)
const DepartmentsIdViewRoute = DepartmentsIdViewRouteImport.update({
  id: '/departments_/$id/view',
  path: '/departments/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdUpdateRoute = DepartmentsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => DepartmentsRoute,
} as any)
const DepartmentsIdDeleteRoute = DepartmentsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => DepartmentsRoute,
} as any)
const CompaniesIdViewRoute = CompaniesIdViewRouteImport.update({
  id: '/companies_/$id/view',
  path: '/companies/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdUpdateRoute = CompaniesIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesIdDeleteRoute = CompaniesIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => CompaniesRoute,
} as any)
const ClientsIdViewRoute = ClientsIdViewRouteImport.update({
  id: '/clients_/$id/view',
  path: '/clients/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdUpdateRoute = ClientsIdUpdateRouteImport.update({
  id: '/$id/update',
  path: '/$id/update',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIdDeleteRoute = ClientsIdDeleteRouteImport.update({
  id: '/$id/delete',
  path: '/$id/delete',
  getParentRoute: () => ClientsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies/$id/view': typeof CompaniesIdViewRoute
  '/departments/$id/delete': typeof DepartmentsIdDeleteRoute
  '/departments/$id/update': typeof DepartmentsIdUpdateRoute
  '/departments/$id/view': typeof DepartmentsIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies/$id/view': typeof CompaniesIdViewRoute
  '/departments/$id/delete': typeof DepartmentsIdDeleteRoute
  '/departments/$id/update': typeof DepartmentsIdUpdateRoute
  '/departments/$id/view': typeof DepartmentsIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/todos': typeof TodosRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/clients/new': typeof ClientsNewRoute
  '/companies/new': typeof CompaniesNewRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/todos/new': typeof TodosNewRoute
  '/users/new': typeof UsersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/$id/delete': typeof ClientsIdDeleteRoute
  '/clients/$id/update': typeof ClientsIdUpdateRoute
  '/clients_/$id/view': typeof ClientsIdViewRoute
  '/companies/$id/delete': typeof CompaniesIdDeleteRoute
  '/companies/$id/update': typeof CompaniesIdUpdateRoute
  '/companies_/$id/view': typeof CompaniesIdViewRoute
  '/departments/$id/delete': typeof DepartmentsIdDeleteRoute
  '/departments/$id/update': typeof DepartmentsIdUpdateRoute
  '/departments_/$id/view': typeof DepartmentsIdViewRoute
  '/todos/$id/delete': typeof TodosIdDeleteRoute
  '/todos/$id/update': typeof TodosIdUpdateRoute
  '/todos_/$id/view': typeof TodosIdViewRoute
  '/users/$id/ban': typeof UsersIdBanRoute
  '/users/$id/delete': typeof UsersIdDeleteRoute
  '/users/$id/unban': typeof UsersIdUnbanRoute
  '/users/$id/update': typeof UsersIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/companies'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/preferences'
    | '/signup'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/clients/new'
    | '/companies/new'
    | '/departments/new'
    | '/todos/new'
    | '/users/new'
    | '/api/auth/$'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies/$id/view'
    | '/departments/$id/delete'
    | '/departments/$id/update'
    | '/departments/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/companies'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/preferences'
    | '/signup'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/clients/new'
    | '/companies/new'
    | '/departments/new'
    | '/todos/new'
    | '/users/new'
    | '/api/auth/$'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies/$id/view'
    | '/departments/$id/delete'
    | '/departments/$id/update'
    | '/departments/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/companies'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/preferences'
    | '/signup'
    | '/todos'
    | '/users'
    | '/wishlist'
    | '/clients/new'
    | '/companies/new'
    | '/departments/new'
    | '/todos/new'
    | '/users/new'
    | '/api/auth/$'
    | '/clients/$id/delete'
    | '/clients/$id/update'
    | '/clients_/$id/view'
    | '/companies/$id/delete'
    | '/companies/$id/update'
    | '/companies_/$id/view'
    | '/departments/$id/delete'
    | '/departments/$id/update'
    | '/departments_/$id/view'
    | '/todos/$id/delete'
    | '/todos/$id/update'
    | '/todos_/$id/view'
    | '/users/$id/ban'
    | '/users/$id/delete'
    | '/users/$id/unban'
    | '/users/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PreferencesRoute: typeof PreferencesRoute
  SignupRoute: typeof SignupRoute
  TodosRoute: typeof TodosRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ClientsIdViewRoute: typeof ClientsIdViewRoute
  CompaniesIdViewRoute: typeof CompaniesIdViewRoute
  DepartmentsIdViewRoute: typeof DepartmentsIdViewRoute
  TodosIdViewRoute: typeof TodosIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof TodosRoute
    }
    '/departments/new': {
      id: '/departments/new'
      path: '/new'
      fullPath: '/departments/new'
      preLoaderRoute: typeof DepartmentsNewRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/users/$id/update': {
      id: '/users/$id/update'
      path: '/$id/update'
      fullPath: '/users/$id/update'
      preLoaderRoute: typeof UsersIdUpdateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/unban': {
      id: '/users/$id/unban'
      path: '/$id/unban'
      fullPath: '/users/$id/unban'
      preLoaderRoute: typeof UsersIdUnbanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/delete': {
      id: '/users/$id/delete'
      path: '/$id/delete'
      fullPath: '/users/$id/delete'
      preLoaderRoute: typeof UsersIdDeleteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id/ban': {
      id: '/users/$id/ban'
      path: '/$id/ban'
      fullPath: '/users/$id/ban'
      preLoaderRoute: typeof UsersIdBanRouteImport
      parentRoute: typeof UsersRoute
    }
    '/todos_/$id/view': {
      id: '/todos_/$id/view'
      path: '/todos/$id/view'
      fullPath: '/todos/$id/view'
      preLoaderRoute: typeof TodosIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/update': {
      id: '/todos/$id/update'
      path: '/$id/update'
      fullPath: '/todos/$id/update'
      preLoaderRoute: typeof TodosIdUpdateRouteImport
      parentRoute: typeof TodosRoute
    }
    '/todos/$id/delete': {
      id: '/todos/$id/delete'
      path: '/$id/delete'
      fullPath: '/todos/$id/delete'
      preLoaderRoute: typeof TodosIdDeleteRouteImport
      parentRoute: typeof TodosRoute
    }
    '/departments_/$id/view': {
      id: '/departments_/$id/view'
      path: '/departments/$id/view'
      fullPath: '/departments/$id/view'
      preLoaderRoute: typeof DepartmentsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id/update': {
      id: '/departments/$id/update'
      path: '/$id/update'
      fullPath: '/departments/$id/update'
      preLoaderRoute: typeof DepartmentsIdUpdateRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/departments/$id/delete': {
      id: '/departments/$id/delete'
      path: '/$id/delete'
      fullPath: '/departments/$id/delete'
      preLoaderRoute: typeof DepartmentsIdDeleteRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/companies_/$id/view': {
      id: '/companies_/$id/view'
      path: '/companies/$id/view'
      fullPath: '/companies/$id/view'
      preLoaderRoute: typeof CompaniesIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id/update': {
      id: '/companies/$id/update'
      path: '/$id/update'
      fullPath: '/companies/$id/update'
      preLoaderRoute: typeof CompaniesIdUpdateRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$id/delete': {
      id: '/companies/$id/delete'
      path: '/$id/delete'
      fullPath: '/companies/$id/delete'
      preLoaderRoute: typeof CompaniesIdDeleteRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/clients_/$id/view': {
      id: '/clients_/$id/view'
      path: '/clients/$id/view'
      fullPath: '/clients/$id/view'
      preLoaderRoute: typeof ClientsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id/update': {
      id: '/clients/$id/update'
      path: '/$id/update'
      fullPath: '/clients/$id/update'
      preLoaderRoute: typeof ClientsIdUpdateRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$id/delete': {
      id: '/clients/$id/delete'
      path: '/$id/delete'
      fullPath: '/clients/$id/delete'
      preLoaderRoute: typeof ClientsIdDeleteRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIdDeleteRoute: typeof ClientsIdDeleteRoute
  ClientsIdUpdateRoute: typeof ClientsIdUpdateRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsNewRoute: ClientsNewRoute,
  ClientsIdDeleteRoute: ClientsIdDeleteRoute,
  ClientsIdUpdateRoute: ClientsIdUpdateRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CompaniesRouteChildren {
  CompaniesNewRoute: typeof CompaniesNewRoute
  CompaniesIdDeleteRoute: typeof CompaniesIdDeleteRoute
  CompaniesIdUpdateRoute: typeof CompaniesIdUpdateRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesNewRoute: CompaniesNewRoute,
  CompaniesIdDeleteRoute: CompaniesIdDeleteRoute,
  CompaniesIdUpdateRoute: CompaniesIdUpdateRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface DepartmentsRouteChildren {
  DepartmentsNewRoute: typeof DepartmentsNewRoute
  DepartmentsIdDeleteRoute: typeof DepartmentsIdDeleteRoute
  DepartmentsIdUpdateRoute: typeof DepartmentsIdUpdateRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsNewRoute: DepartmentsNewRoute,
  DepartmentsIdDeleteRoute: DepartmentsIdDeleteRoute,
  DepartmentsIdUpdateRoute: DepartmentsIdUpdateRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface TodosRouteChildren {
  TodosNewRoute: typeof TodosNewRoute
  TodosIdDeleteRoute: typeof TodosIdDeleteRoute
  TodosIdUpdateRoute: typeof TodosIdUpdateRoute
}

const TodosRouteChildren: TodosRouteChildren = {
  TodosNewRoute: TodosNewRoute,
  TodosIdDeleteRoute: TodosIdDeleteRoute,
  TodosIdUpdateRoute: TodosIdUpdateRoute,
}

const TodosRouteWithChildren = TodosRoute._addFileChildren(TodosRouteChildren)

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
  UsersIdBanRoute: typeof UsersIdBanRoute
  UsersIdDeleteRoute: typeof UsersIdDeleteRoute
  UsersIdUnbanRoute: typeof UsersIdUnbanRoute
  UsersIdUpdateRoute: typeof UsersIdUpdateRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
  UsersIdBanRoute: UsersIdBanRoute,
  UsersIdDeleteRoute: UsersIdDeleteRoute,
  UsersIdUnbanRoute: UsersIdUnbanRoute,
  UsersIdUpdateRoute: UsersIdUpdateRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  LoginRoute: LoginRoute,
  PreferencesRoute: PreferencesRoute,
  SignupRoute: SignupRoute,
  TodosRoute: TodosRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ClientsIdViewRoute: ClientsIdViewRoute,
  CompaniesIdViewRoute: CompaniesIdViewRoute,
  DepartmentsIdViewRoute: DepartmentsIdViewRoute,
  TodosIdViewRoute: TodosIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
